# Generated by Django 4.2 on 2023-04-29 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Receitas',
            fields=[
                ('post_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('post_nome', models.CharField(max_length=80)),
                ('post_ingretientes', models.CharField(max_length=100)),
                ('post_preparo', models.CharField(max_length=255)),
                ('post_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
