# Generated by Django 4.2 on 2023-04-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_alter_post_receitas_post_ingretientes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_receitas',
            name='post_ingretientes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post_receitas',
            name='post_preparo',
            field=models.TextField(),
        ),
    ]
