# Generated by Django 4.2 on 2023-04-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_rename_post_ingretientes_post_receitas_post_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_receitas',
            name='post_ingredientes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post_receitas',
            name='post_nome',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='post_receitas',
            name='post_preparo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
