# Generated by Django 4.2 on 2023-04-30 03:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receitas', '0005_alter_post_receitas_post_ingredientes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_Receitas',
            new_name='PostReceitas',
        ),
    ]
