# Generated by Django 4.2 on 2023-05-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0009_alter_postreceitas_post_ingredientes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreceitas',
            name='post_ingredientes',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='postreceitas',
            name='post_preparo',
            field=models.TextField(max_length=50),
        ),
    ]
