# Generated by Django 4.2 on 2023-05-01 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receitas', '0010_alter_postreceitas_post_ingredientes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreceitas',
            name='post_ingredientes',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postreceitas',
            name='post_nome',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='postreceitas',
            name='post_preparo',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postreceitas',
            name='post_usuario_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
