# Generated by Django 4.2 on 2023-05-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0012_alter_postreceitas_post_ingredientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreceitas',
            name='post_publicado',
            field=models.BooleanField(default=False),
        ),
    ]
