# Generated by Django 4.2 on 2023-05-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0013_postreceitas_post_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreceitas',
            name='post_tempo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
