# Generated by Django 4.2 on 2023-05-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0015_alter_postreceitas_post_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreceitas',
            name='post_ingredientes',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postreceitas',
            name='post_preparo',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
