# Generated by Django 4.2 on 2023-05-03 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receitas', '0017_alter_postreceitas_post_ingredientes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('cat_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_nome', models.CharField(max_length=35, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='postreceitas',
            name='post_codigo',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='postreceitas',
            name='post_nome',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome da receita'),
        ),
        migrations.AlterField(
            model_name='postreceitas',
            name='post_publicado',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='postreceitas',
            name='post_usuario_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='postreceitas',
            name='post_categoria_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='receitas.categoriamodel'),
        ),
    ]
