# Generated by Django 4.2 on 2023-05-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0018_categoriamodel_alter_postreceitas_post_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreceitas',
            name='post_ingredientes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='postreceitas',
            name='post_preparo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
